version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "monthly"
