{
  "formatVersion": "1.1",
  "component": {
    "group": "org.kodein.di",
    "module": "kodein-di-framework-ktor-server-jvm",
    "version": "7.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.kodein.di",
          "module": "kodein-di",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-di-framework-ktor-server-jvm-7.12.0.jar",
          "url": "kodein-di-framework-ktor-server-jvm-7.12.0.jar",
          "size": 22386,
          "sha512": "608c0e77d6cedcc6f62125396df2eb24d8e4beec04444fbaad9d1237a3e5980b9957a11af60346287f4bb3175b4cb066b96c22f7aea165e620e14ec3b621af51",
          "sha256": "60f03cf3d5b4fc9454bed48ece30d921921dc1a49084a56fb3f2e720188955d5",
          "sha1": "c4947f85c8aa5e622d9aad49ef3ad1de27f40ff1",
          "md5": "4ea7cce88b6ff38ff75e54c516b005a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-sessions",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.kodein.di",
          "module": "kodein-di",
          "version": {
            "requires": "7.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "kodein-di-framework-ktor-server-jvm-7.12.0.jar",
          "url": "kodein-di-framework-ktor-server-jvm-7.12.0.jar",
          "size": 22386,
          "sha512": "608c0e77d6cedcc6f62125396df2eb24d8e4beec04444fbaad9d1237a3e5980b9957a11af60346287f4bb3175b4cb066b96c22f7aea165e620e14ec3b621af51",
          "sha256": "60f03cf3d5b4fc9454bed48ece30d921921dc1a49084a56fb3f2e720188955d5",
          "sha1": "c4947f85c8aa5e622d9aad49ef3ad1de27f40ff1",
          "md5": "4ea7cce88b6ff38ff75e54c516b005a1"
        }
      ]
    }
  ]
}
