name: Scan Kodex

on:
  workflow_dispatch:
    branches:
      - kodex
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: INFO
      tag:
        description: 'CLI image tag'
        required: true
        default: latest
  schedule:
    - cron: '0 0 * * *'

env:
  MONGO_STRING: ${{ secrets.MONGO_STRING }}
  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}/kodex/cli
  TAG: ${{ github.event.inputs.tag }}
  LOG_LEVEL: ${{ github.event.inputs.logLevel }}

concurrency:
  group: scan-kodex
  cancel-in-progress: false

permissions:
  packages: read

jobs:
  scan:
    runs-on: ubuntu-latest
    environment: kodex
    strategy:
      max-parallel: 10
      matrix:
        repository:
          - 'mavenCentral'
        options:
          - '--include=com'
          - '--include=org'
          - '--include=io'
          - '--from=a --to=c --exclude=com'
          - '--from=d --to=f'
          - '--from=g --to=l --exclude=io'
          - '--from=m --to=p --exclude=org'
          - '--from=q --to=t'
          - '--from=u --to=z'
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: |
          docker run -a stderr -a stdout \
            -e="LOG_LEVEL=${LOG_LEVEL:-INFO}" \
            -e="MONGO_STRING" \
            -e="MONGO_DATABASE" \
            "${{ env.REGISTRY }}/${{ env.IMAGE }}:${TAG:-latest}" scan ${{ matrix.repository }} ${{ matrix.options }}

  capture:
    needs: [ scan ]
    runs-on: ubuntu-latest
    environment: kodex
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: |
          docker run -a stderr -a stdout \
            -e="LOG_LEVEL=${LOG_LEVEL:-INFO}" \
            -e="MONGO_STRING" \
            -e="MONGO_DATABASE" \
            "${{ env.REGISTRY }}/${{ env.IMAGE }}:${TAG:-latest}" capture
