name: Scan

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: INFO
  schedule:
    - cron: '0 0 * * *'

env:
  API_URL: https://kamp.azurewebsites.net
  ADMIN_USER: ${{ secrets.API_ADMIN_USER }}
  ADMIN_PASSWORD: ${{ secrets.API_ADMIN_PASSWORD }}
  IMAGE: docker.pkg.github.com/mpetuska/kamp/scanner:latest
  LOG_LEVEL: ${{ github.event.inputs.logLevel }}

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        repository:
          - 'mavenCentral'
        options:
          - '-i com'
          - '-i org'
          - '-e com -f a -t c'
          - '-f d -t f'
          - '-f g -t l'
          - '-e org -f m -t p'
          - '-f q -t t'
          - '-f u -t z'
    steps:
      - uses: docker/login-action@v2.0.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: docker run -a stderr -a stdout -e "LOG_LEVEL=${LOG_LEVEL:-INFO}" -e API_URL -e ADMIN_USER -e ADMIN_PASSWORD ${{ env.IMAGE }} ${{ matrix.repository }} ${{ matrix.options }}
