name: Refresh Terraform State

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  refresh-Infrastructure:
    runs-on: ubuntu-latest
    name: Refresh Main Infrastructure
    env:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
      MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Terraform environment
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 0.14.9
      - name: Terraform init
        run: terraform init
        working-directory: infra
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7
      - name: Terraform refresh
        run: terraform refresh
        working-directory: infra
        env:
          TF_VAR_docker_registry_username: ${{ secrets.GH_PKG_USER }}
          TF_VAR_docker_registry_password: ${{ secrets.GH_PKG_PASSWORD }}
          TF_VAR_docker_image_tag: docker.pkg.github.com/mpetuska/kodex/app:sha-${{ steps.short-sha.outputs.sha }}
